* Progragm gengtr1b2b
* 
*
* as on 6 Aug 2017


* * * * For b2b * * * *
* Require fields
* GST
* Invoice No
* Inv Dt
* Invoice Val
* Place of Supply
* reverse charge
* invoice type
* E commerce GST
* tax rate
* taxable value
* cess
* * * * * B2B  End * * * *



* * * * * For b2cl * * * *
*
* Invoice No
* Invoice Dt
* Invoice Val
* Place of Supply
* tax Rate
* taxable Val
* Cess
* E Comm GSTIN
** * * * * *

* * * * * * For B2cS * * * * *
*
* Type : E or OE
* Place of Supply
* tax Rate
* taxable Value
* Cess
* E comm Gstin
* * * * * * * * * *

* * * * * * * CDNR * * * * * * *
* GSTIN
* InvNo
* InvDt
* NoteNo
* NoteDt
* DocType
* Reason
* Place of Supply
* VouValue
* Taxable Amt
* Taxable Rate
* Cess
* PreGST
* * * * * * * * * * * * * * * *


* * * * * * * CDNUR * * * * * * *
* URType
* VouNo
* VouDt
* DocType
* InvNo
* InvDt
* Reason
* POS
* Vou Value
* Taxable Rate
* Taxable Value
* Cess
* PreGST
* * * * * * * * * * * * * * * *


* * * * * * * AT * * * * * * *
* POS
* Rate
* Adv Received
* Cess
* * * * * * * * * * * * * * * *


* * * * * * * ATADJ * * * * * * *
* POS
* Rate
* Amt Adjusted
* Cess
* * * * * * * * * * * * * * * *


* * * * * * * HSN * * * * * * *
* HSN
* Description
* UQC
* Ttl Qty
* Ttl Val
* Txbl Val
* IGST
* CGST
* SGST
* Cess
* * * * * * * * * * * * * * * *


* * * * * * * DOCS * * * * * * *
* Nature of Docs
* Sr No from
* Sr No To
* Total Nos
* Cancelled
* * * * * * * * * * * * * * * *

